### ISSUE TITLE
Run example which uses core library

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/gi-yagit#4]

**Comment by pawek001** [comment]
Windows run is bit complicated: i mentioned it in [https://github.com/DataMedSci/gi-yagit/tree/windows-development-only](url), but example work with this. Results:
![image](https://user-images.githubusercontent.com/58525337/119035663-186b4d00-b9b0-11eb-81b2-3c587b23002c.png)
![image](https://user-images.githubusercontent.com/58525337/119036551-25d50700-b9b1-11eb-8984-f9210053c710.png)

**Comment by pawek001** [comment]
Linux: in this operating systems to run is simple: just run ./deploy.sh in terminal and them ./core_2d_client in examples. Result: 
![image](https://user-images.githubusercontent.com/58525337/119037065-cd523980-b9b1-11eb-8e87-87850d93d7b5.png)
