### ISSUE TITLE
https://github.com/TheTryton/libsimdpp/commit/7bdb659707a0d753918a7f6d75a581699ee2f34e. This one line doesn't compile for some reason (too long to explain) under the ubuntu gcc (mingw doesn't complain about it).

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/gi-yagit#40]
https://github.com/TheTryton/libsimdpp/commit/7bdb659707a0d753918a7f6d75a581699ee2f34e. This one line doesn't compile for some reason (too long to explain) under the ubuntu gcc (mingw doesn't complain about it).

_Originally posted by @TheTryton in https://github.com/DataMedSci/gi-yagit/pull/32#r761076218_

**Comment by michal367** [comment]
outdated
