### ISSUE TITLE
Test if GUI runs with example files

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/gi-yagit#6]

**Comment by pawek001** [comment]
![image](https://user-images.githubusercontent.com/58525337/119041150-8e72b280-b9b6-11eb-81ef-a36859edbf0b.png)

**Comment by pawek001** [comment]
After some proper changes i managed to run gui on windows machine with some needed changes (need to copy 2 .ddl files to System32 directory) but i get results
![image](https://user-images.githubusercontent.com/58525337/119099114-daedda80-ba16-11eb-8459-f46bf918e588.png)

**Comment by grzanka** [comment]
Please note that copying anything to `System32` will be unacceptable for future users of this GUI
