### ISSUE TITLE
Check if core library compiles on Windows

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/gi-yagit#8]
Requires proper CMake, as pure makes are a bit useless on Windows.

CMake should generate MS Visual Studio solutions which then should be used for compilation (from command line, or by CI) !

**Comment by grzanka** [comment]
Use `cmake --build`

**Comment by pawek001** [comment]
![image](https://user-images.githubusercontent.com/58525337/118150183-8f35a280-b412-11eb-9ff0-b4da5443f32d.png)

**Comment by grzanka** [comment]
Was the compilation successful ?

**Comment by pawek001** [comment]
yes, it was 
![image](https://user-images.githubusercontent.com/58525337/119040077-443d0180-b9b5-11eb-8d72-31e354cb5912.png)
![image](https://user-images.githubusercontent.com/58525337/119040152-59199500-b9b5-11eb-9dfc-4a0a05d16baf.png)
![image](https://user-images.githubusercontent.com/58525337/119040022-35eee580-b9b5-11eb-98c6-69dcc7a59bfa.png)
